app = "fbl-marketing-site"
primary_region = "dfw"

[build]
dockerfile = "./Dockerfile"

[http_service]
internal_port = 8043
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
