# fly.toml app configuration file generated for fbl-marketing-site on 2023-08-17T19:08:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fbl-marketing-site"
primary_region = "dfw"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
