[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection ='''1,
    mode=block'''
    Content-Security-Policy = '''
    default-src 'self';
    img-src 'self' data:;
    connect-src 'self';
    style-src 'self' 'unsafe-inline';
    style-src-elem 'self' 'unsafe-inline';
    script-src 'self' https://analytics.umami.is https://challenges.cloudflare.com 'unsafe-inline';
    script-src-elem 'self' https://analytics.umami.is https://challenges.cloudflare.com 'unsafe-inline';
    '''
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"


[[headers]]
  for = "/*.woff2"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public'''
