name: ⚡️ Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
env:
  NODE_VERSION: 18.17.0
  PUBLIC_GIT_BRANCH: ${{ github.ref_name}}
  PUBLIC_GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  deploy_staging:
    name: 🚧 Deploy Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    environment: preview
    steps:
      - name: ↧ Checkout code
        uses: actions/checkout@v3

      - name: ⬡ Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ⬣ Install dependencies
        run: npm ci

      - name: 🛠️ Build site
        run: npm run build
        env:
          PUBLIC_TURNSTILE_SITEKEY: ${{ vars.PUBLIC_TURNSTILE_SITEKEY }}
          PUBLIC_UMAMI_WEBSITE_ID: ${{ vars.PUBLIC_UMAMI_WEBSITE_ID }}

      - name: ☁️ Deploy to Cloudflare
        uses: cloudflare/pages-action@v1.5.0
        with:
          directory: dist
          wranglerVersion: "3"
          branch: ${{ github.ref_name}}
          projectName: fbl-marketing-site
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy_prod:
    name: ⚡️ Deploy Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://friendlybearlabs.com
    steps:
      - name: ↧ Checkout code
        uses: actions/checkout@v3

      - name: ⬡ Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ⬣ Install dependencies
        run: npm ci

      - name: 🛠️ Build site
        run: npm run build
        env:
          PUBLIC_TURNSTILE_SITEKEY: ${{ vars.PUBLIC_TURNSTILE_SITEKEY }}
          PUBLIC_UMAMI_WEBSITE_ID: ${{ vars.PUBLIC_UMAMI_WEBSITE_ID }}

      - name: ☁️ Deploy to Cloudflare
        uses: cloudflare/pages-action@v1.5.0
        with:
          directory: dist
          wranglerVersion: "3"
          branch: ${{ github.ref_name}}
          projectName: fbl-marketing-site
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
