name: 🧪 Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging

env:
  NODE_VERSION: 18.17.0
  PUBLIC_GIT_BRANCH: ${{ github.ref_name }}
  PUBLIC_GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  deploy:
    name: ⚡️ Deploy
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: ↧ Checkout code
        uses: actions/checkout@v3

      - name: ⬣ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ⬣ Install dependencies
        run: npm ci

      - name: 🛠️ Build site
        run: npm run build

      - name: ☁️ Deploy to Cloudflare
        uses: cloudflare/pages-action@v1.5.0
        with:
          directory: dist
          wranglerVersion: "3"
          branch: ${{ github.ref_name }}
          projectName: fbl-marketing-site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
